-- RecoverAI Named Analytics Queries for Exasol Personal

-- 1. High-level Revenue Recovery KPI Summary
SELECT 
    COUNT(*) AS TOTAL_PAYMENTS,
    SUM(CASE WHEN STATUS = 'FAILED' THEN AMOUNT ELSE 0 END) AS REVENUE_AT_RISK,
    SUM(CASE WHEN STATUS = 'RECOVERED' THEN AMOUNT ELSE 0 END) AS RECOVERED_REVENUE,
    ROUND(
        (SUM(CASE WHEN STATUS = 'RECOVERED' THEN AMOUNT ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN STATUS IN ('FAILED', 'RECOVERED') THEN AMOUNT ELSE 0 END), 0)) * 100, 2
    ) AS RECOVERY_RATE_PCT,
    COUNT(CASE WHEN STATUS = 'FAILED' THEN 1 END) AS FAILED_COUNT,
    COUNT(CASE WHEN STATUS = 'RECOVERED' THEN 1 END) AS RECOVERED_COUNT
FROM RECOVERAI.PAYMENTS;

-- 2. Failure Reason Distribution & Financial Impact
SELECT 
    COALESCE(FAILURE_REASON, 'Unknown') AS FAILURE_REASON,
    COUNT(*) AS FAILURE_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT_LOST,
    ROUND(AVG(AMOUNT), 2) AS AVG_AMOUNT
FROM RECOVERAI.PAYMENTS
WHERE STATUS IN ('FAILED', 'ABANDONED')
GROUP BY FAILURE_REASON
ORDER BY TOTAL_AMOUNT_LOST DESC;

-- 3. Recovery Rate and Success by Payment Method
SELECT 
    PAYMENT_METHOD,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    COUNT(CASE WHEN STATUS = 'FAILED' THEN 1 END) AS FAILED_COUNT,
    COUNT(CASE WHEN STATUS = 'RECOVERED' THEN 1 END) AS RECOVERED_COUNT,
    ROUND(
        COUNT(CASE WHEN STATUS = 'RECOVERED' THEN 1 END) * 100.0 / 
        NULLIF(COUNT(CASE WHEN STATUS IN ('FAILED', 'RECOVERED') THEN 1 END), 0), 1
    ) AS RECOVERY_SUCCESS_RATE_PCT
FROM RECOVERAI.PAYMENTS
GROUP BY PAYMENT_METHOD
ORDER BY RECOVERY_SUCCESS_RATE_PCT DESC;

-- 4. Recovery Agent Performance by Recommended Action
SELECT 
    CHOSEN_ACTION,
    COUNT(*) AS TOTAL_ACTIONS,
    SUM(CASE WHEN STATUS = 'RESOLVED' THEN 1 ELSE 0 END) AS SUCCESSFUL_RECOVERIES,
    SUM(RECOVERED_AMOUNT) AS TOTAL_RECOVERED_AMOUNT,
    ROUND(AVG(RECOVERY_PROBABILITY), 1) AS AVG_CONFIDENCE_SCORE
FROM RECOVERAI.RECOVERY_CASES
GROUP BY CHOSEN_ACTION
ORDER BY TOTAL_RECOVERED_AMOUNT DESC;

-- 5. Daily Recovered Revenue Trend (Last 30 Days)
SELECT 
    CAST(CREATED_AT AS DATE) AS EVENT_DATE,
    SUM(CASE WHEN STATUS = 'FAILED' THEN AMOUNT ELSE 0 END) AS DAILY_FAILED_AMT,
    SUM(CASE WHEN STATUS = 'RECOVERED' THEN AMOUNT ELSE 0 END) AS DAILY_RECOVERED_AMT
FROM RECOVERAI.PAYMENTS
GROUP BY CAST(CREATED_AT AS DATE)
ORDER BY EVENT_DATE ASC;
