-- RecoverAI Exasol Schema Definition
-- Creates schema and tables for payments, recovery cases, and immutable audit log

CREATE SCHEMA IF NOT EXISTS RECOVERAI;
OPEN SCHEMA RECOVERAI;

-- Payments Table
CREATE OR REPLACE TABLE PAYMENTS (
    PAYMENT_ID VARCHAR(64) PRIMARY KEY,
    ORDER_ID VARCHAR(64),
    CUSTOMER_NAME VARCHAR(128),
    CUSTOMER_EMAIL VARCHAR(128),
    CUSTOMER_PHONE VARCHAR(32),
    AMOUNT DECIMAL(12,2),
    CURRENCY VARCHAR(8) DEFAULT 'INR',
    STATUS VARCHAR(32), -- 'FAILED', 'SUCCESS', 'ABANDONED', 'RECOVERED', 'IN_RECOVERY'
    FAILURE_REASON VARCHAR(256),
    FAILURE_CODE VARCHAR(64),
    PAYMENT_METHOD VARCHAR(32), -- 'UPI', 'CARD', 'NETBANKING', 'WALLET'
    ATTEMPT_COUNT INT DEFAULT 1,
    LAST_ATTEMPT_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Recovery Cases Table
CREATE OR REPLACE TABLE RECOVERY_CASES (
    CASE_ID VARCHAR(64) PRIMARY KEY,
    PAYMENT_ID VARCHAR(64),
    STATUS VARCHAR(32), -- 'OPEN', 'RESOLVED', 'ABANDONED', 'STOPPED'
    RECOVERY_PROBABILITY DECIMAL(5,2),
    CHOSEN_ACTION VARCHAR(64), -- 'RETRY_PAYMENT', 'SEND_RECOVERY_LINK', 'UPDATE_PAYMENT_METHOD', 'SEND_REMINDER', 'MANUAL_REVIEW'
    REASON VARCHAR(512),
    SHOULD_STOP BOOLEAN DEFAULT FALSE,
    ATTEMPTS_MADE INT DEFAULT 0,
    RECOVERED_AMOUNT DECIMAL(12,2) DEFAULT 0.00,
    INITIATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT TIMESTAMP,
    CONSTRAINT FK_REC_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS(PAYMENT_ID)
);

-- Audit Log Table
CREATE OR REPLACE TABLE AUDIT_LOGS (
    LOG_ID VARCHAR(64) PRIMARY KEY,
    PAYMENT_ID VARCHAR(64),
    EVENT_TYPE VARCHAR(64),
    ACTION_TAKEN VARCHAR(64),
    DETAILS VARCHAR(2000),
    PERFORMED_BY VARCHAR(64) DEFAULT 'AI_AGENT',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
